### ISSUE TITLE
Debug Training Script

### ISSUE THREAD

**Issue by work4cs** [Imageomics/HDR-anomaly-challenge#36]
Debug training script in [repo](https://github.com/Imageomics/HDR-anomaly-challenge-sample/tree/main)

**Comment by Link7808** [comment]
Bug has been fixed. Should we add sample submission to this [https://github.com/Imageomics/HDR-anomaly-challenge-sample/tree/main](repo)

**Comment by egrace479** [comment]
> Bug has been fixed. Should we add sample submission to this [repo](https://github.com/Imageomics/HDR-anomaly-challenge-sample/tree/main)

Yes, please update it.

**Comment by Link7808** [comment]
> > Bug has been fixed. Should we add sample submission to this [repo](https://github.com/Imageomics/HDR-anomaly-challenge-sample/tree/main)
> 
> Yes, please update it.

Added
